name: Deploy API to Render

on:
  push:
    branches:
      - main  # Déclenche le déploiement à chaque push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Déploiement sur Render via Webhook
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cva46fl6l47c739heqgg?key=sTifBkwDrH4"
